# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dc44b9dae3aff2ba16e6982d545d9be25497850630cbd2187f43fd7e67e81ef34e418aceed2b1c63ef73d4219e638e254d7b7c20eced18924512326b59fa161

test:
  secret_key_base: afb52a6fdb1c6cb4960bb0108d77bc8d6203bd3b831a672e7f88c1ed57e36ad6fe122f0f9c15d4ab3fa61289c1ad462e2a58534e57f1e5d95273756b17f2cf46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
